/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GrvOkFjcSlx
 */


export function Certifications() {
  return (<>
    <div className="py-12 sm:py-16 lg:py-24">
      <div className="container px-4">
        <div className="grid gap-6 lg:gap-8">
          <div className="grid items-center gap-6 px-10 md:grid-cols-1 lg:gap-8">
            <div className="flex flex-col justify-center space-y-3">
              <h1 className="text-3xl font-bold tracking-tight">Quality Certifications</h1>
              <p className="text-gray-600 dark:text-gray-400">
                ISO 9001:2015, ISO 14001:2015, and IATF 16949:2016 are internationally recognized standards that provide requirements
                for quality management systems, environmental management systems, and quality management systems for
                the automotive industry, respectively. Achieving certification demonstrates an organization&apos;s
                commitment to meeting the highest standards of quality, environmental sustainability, and automotive
                quality management.
              </p>
            </div>

          </div>
          <div className="grid items-start gap-6 pt-10 md:grid-cols-3 lg:gap-8">
            <div className="flex flex-col items-center space-y-3">
              <CheckCircleIcon className="w-12 h-12 text-blue-500" />
              <h2 className="text-xl font-semibold tracking-tight">ISO 9001</h2>
              <p className="text-sm text-center text-gray-500 dark:text-gray-400">
                The ISO 9001 standard focuses on quality management and ensuring that an organization meets the needs
                of its customers and other stakeholders. It provides a framework for establishing quality policies and
                objectives, managing resources, and continuously improving processes.
              </p>
            </div>
            <div className="flex flex-col items-center space-y-3">
              <CheckCircleIcon className="w-12 h-12 text-blue-500" />
              <h2 className="text-xl font-semibold tracking-tight">ISO 14001</h2>
              <p className="text-sm text-center text-gray-500 dark:text-gray-400">
                The ISO 14001 standard focuses on environmental management and helping organizations minimize their
                environmental impact. This includes implementing an effective environmental management system,
                identifying and complying with legal and other requirements, and continually improving environmental
                performance.
              </p>
            </div>
            <div className="flex flex-col items-center space-y-3">
              <CheckCircleIcon className="w-12 h-12 text-blue-500" />
              <h2 className="text-xl font-semibold tracking-tight">IATF 16949</h2>
              <p className="text-sm text-center text-gray-500 dark:text-gray-400">
                The IATF 16949 standard is designed for organizations in the automotive industry and is based on the
                ISO 9001:2015 standard. It includes additional requirements specific to automotive quality management, such
                as defect prevention, variation reduction, and waste elimination.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div className="py-12 border-t dark:bg-gray-800 lg:py-24">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The ISO 9001 Certification Process</h2>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our team of experienced consultants will guide you through the process, ensuring that your organization
              meets the requirements of the ISO standards. We offer a range of services to help you achieve
              certification, including gap analysis, documentation, training, and audits.
            </p>
          </div>
          <ul className="grid gap-4 py-4 list-disc md:gap-6 md:py-6">
            <li>
              <h3 className="text-xl font-bold tracking-tight">Gap Analysis and Readiness Assessment</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our consultants will conduct a thorough assessment of your organization’s current processes and
                practices to identify any gaps that need to be addressed to meet the requirements of the ISO
                standards.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Documentation and Process Improvement</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Once the gaps have been identified, our team will work with you to develop and implement the necessary
                documentation and process improvements to ensure compliance with the ISO standards.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Training and Employee Engagement</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We believe that achieving ISO certification is not just about meeting the requirements of the
                standards, but also about creating a culture of quality and continuous improvement within your
                organization. That’s why we offer training and support to help your employees understand the ISO
                standards and their role in the certification process.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Internal Audits and Compliance Checks</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our team will conduct internal audits and compliance checks to ensure that your organization is
                meeting the requirements of the ISO standards. We will identify any areas of non-compliance and work
                with you to address them before the external certification audit.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div className="py-12 border-t lg:py-24">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The ISO 14001 Certification Process</h2>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our team of experienced consultants will guide you through the process, ensuring that your organization
              meets the requirements of the ISO standards. We offer a range of services to help you achieve
              certification, including environmental review, documentation, training, and audits.
            </p>
          </div>
          <ul className="grid gap-4 py-4 list-disc md:gap-6 md:py-6">
            <li>
              <h3 className="text-xl font-bold tracking-tight">Environment Review</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Conducting an initial environmental review to understand the organization&apos;s environmental aspects
                and impacts.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Develpoing Environmental Management System</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Developing an environmental management system that aligns with the requirements of the ISO 14001
                standard.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Implementing Environmental Management System</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Implementing the environmental management system and ensuring compliance with legal and other
                requirements.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Internal Audits and Compliance Checks</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our team will conduct internal audits and compliance checks to evaluate the effectiveness of the environmental 
                management system. We will identify any areas of non-compliance and work
                with you to address them before the external certification audit. Engaging an accredited certification body to conduct an external audit and grant ISO 14001
                certification.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div className="py-12 border-t dark:bg-gray-800 lg:py-24">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The IATF 16949 Certification Process</h2>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our team of experienced consultants will guide you through the process, ensuring that your organization
              meets the requirements of the IATF 16949 standards. We offer a range of services to help you achieve
              certification, including gap analysis, QMS documentation, training, and audits.
            </p>
          </div>
          <ul className="grid gap-4 py-4 list-disc md:gap-6 md:py-6">
            <li>
              <h3 className="text-xl font-bold tracking-tight">Gap Analysis and QMS Assessment</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our consultants will conduct a thorough assessment of your organization’s current processes and
                practices to identify any gaps that need to be addressed to meet the requirements of the IATF 16949
                standards. Based on the IATF 16949 requirements implement a QMS within your organization. Document the QMS processes
                and key performance indicators (KPIs).
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Training and Awareness</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We believe that achieving IATF certification is not just about meeting the requirements of the
                standards, but also about creating a culture of quality and continuous improvement within your
                organization. Train your organization on IATF 16949 principles and practices. Ensure that everyone
                understands their roles and responsibilities with the QMS
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Conduct Internal Audits</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our team will conduct internal audits and compliance checks to ensure that your organization is
                meeting the requirements of the IATF standards. Regular audit your QMS using process auditing techniques.
                Identify any gaps or noncorformities and address them properly
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Accredited Certification Body and On-Site Audit</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Finally contact a certification body accredited by the IATF and apply for a certification. Our team will guide your
                organization through the on-site audit.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>

    {/* <div className="py-12 border-t dark:bg-gray-800 sm:py-16 lg:py-24">
      <div className="container px-4">
        <div className="grid gap-6 lg:gap-8">
        <h1 className="text-3xl font-bold tracking-tight">The Process</h1>
          <div className="grid items-center gap-6 pb-10 md:grid-cols-1 lg:gap-8">
            <div className="flex flex-col justify-center space-y-3">
              <h1 className="text-3xl font-bold tracking-tight">ISO 9001:2015 Certification</h1>
              <p className="text-gray-600 dark:text-gray-400">
                The process of obtaining ISO 9001:2015 certification involves several steps, including:
                <ul>
                  <li>Conducting a gap analysis to assess current processes and identify areas for improvement.</li>
                  <li>
                    Developing a quality management system that meets the requirements of the ISO 9001:2015 standard.
                  </li>
                  <li>
                    Implementing the quality management system and ensuring that it is followed throughout the
                    organization.
                  </li>
                  <li>Conducting internal audits to assess the effectiveness of the quality management system.</li>
                  <li>
                    Engaging an accredited certification body to perform an external audit and issue the ISO 9001:2015
                    certification.
                  </li>
                </ul>
              </p>
            </div>
            {/* <div className="flex justify-center">
              <img
                alt="ISO 9001:2015 Certification Process"
                className="object-cover rounded-xl"
                height="266"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/266",
                  objectFit: "cover",
                }}
                width="400" />
            </div> */}
          {/* </div>
          <div className="grid items-center gap-6 pb-10 md:grid-cols-1 lg:gap-8">
            <div className="flex flex-col justify-center space-y-3">
              <h1 className="text-3xl font-bold tracking-tight">ISO 14001:2015 Certification</h1>
              <p className="text-gray-600 dark:text-gray-400">
                The process of obtaining ISO 14001:2015 certification involves several steps, including:
                <ul>
                  <li>
                    Conducting an initial environmental review to understand the organization's environmental aspects
                    and impacts.
                  </li>
                  <li>
                    Developing an environmental management system that aligns with the requirements of the ISO 14001:2015
                    standard.
                  </li>
                  <li>
                    Implementing the environmental management system and ensuring compliance with legal and other
                    requirements.
                  </li>
                  <li>
                    Conducting internal audits to evaluate the effectiveness of the environmental management system.
                  </li>
                  <li>
                    Engaging an accredited certification body to conduct an external audit and grant ISO 14001:2015
                    certification.
                  </li>
                </ul>
              </p>
            </div> */}
            {/* <div className="flex justify-center">
              <img
                alt="ISO 14001:2015 Certification Process"
                className="object-cover rounded-xl"
                height="266"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/266",
                  objectFit: "cover",
                }}
                width="400" />
            </div> */}
          {/* </div>
          <div className="grid items-center gap-6 md:grid-cols-1 lg:gap-8">
            <div className="flex flex-col justify-center space-y-3">
              <h1 className="text-3xl font-bold tracking-tight">IATF 16949:2016 Certification</h1>
              <p className="text-gray-600 dark:text-gray-400">
                The process of obtaining IATF 16949:2016 certification involves several steps, including:
                <ul>
                  <li>Understanding the specific requirements of the automotive industry.</li>
                  <li>Implementing quality management systems tailored to automotive quality standards.</li>
                  <li>Conducting audits to ensure compliance with IATF 16949:2016 standards.</li>
                  <li>Continuous improvement and monitoring of processes to meet automotive quality requirements.</li>
                  <li>Engaging with certification bodies for assessment and certification.</li>
                </ul>
              </p>
            </div> */}
            {/* <div className="flex justify-center">
              <img
                alt="IATF 16949:2016 Certification Process"
                className="object-cover rounded-xl"
                height="266"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/266",
                  objectFit: "cover",
                }}
                width="400" />
            </div> */}
          {/* </div>
        </div>
      </div>
    </div> */}
  </>);
}


function CheckCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>)
  );
}
