/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rVd7u4tCrGc
 */
'use client'
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useForm } from "react-hook-form"
import { sendEmail } from "../../../utils/send-email"

const Contact = () => {
  
  const { register, handleSubmit } = useForm();
  const onSubmit = (data) => sendEmail(data)



  return (
    (<div className="w-full px-4 py-12 md:py-24 lg:px-6">
      <div className="container max-w-full py-6 prose">
        <div className="space-y-2">
          <h1 className="text-4xl font-bold">Talk to our Quality Certification team</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Fill out the form below and we&apos;ll get back to you as soon as possible.
          </p>
        </div>
      </div>
      <form onSubmit={handleSubmit(onSubmit)}>
      <div className="container space-y-8">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-1">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input {...register("name")} placeholder="Enter your name" type="text" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input {...register("email")} placeholder="Enter your email" type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="phone">Phone</Label>
          <Input {...register("phone")} placeholder="Enter your phone number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company">Company</Label>
          <Input {...register("company")} placeholder="Enter your company name" />
        </div>
        {/* <div className="space-y-2">
           <Label htmlFor="iso">ISO standard of interest</Label>
           <Select>
             <SelectTrigger aria-label="ISO standard of interest" id="iso">
               <SelectValue placeholder="Select" />
             </SelectTrigger>
             <SelectContent>
               <SelectItem value="9001">ISO 9001:2015</SelectItem>
               <SelectItem value="14001">ISO 14001:2015</SelectItem>
               <SelectItem value="45001">IATF 16949:2016</SelectItem>
             </SelectContent>
           </Select>
        </div> */}
        <div className="space-y-2">
          <Label htmlFor="message">Message</Label>
          <Textarea {...register("message")} className="min-h-[100px]" placeholder="Enter your message" />
        </div>
        <Button>Send message</Button>
      </div>
      </form>
    </div>)
  );
}

export default Contact;
