/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LUx0PYzl2N5
 */
import Link from "next/link"

export function Services() {
  return (<>
    <div className="py-12 lg:py-24">
      <div className="px-4 md:px-12">
        <div className="grid gap-12 lg:grid-cols-2 lg:gap-24">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Achieve ISO Certification with Confidence
              </h2>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our team of experienced consultants will guide you through the process, ensuring that your
                organization meets the requirements of the ISO standards. We offer a range of services to help you
                achieve certification, including gap analysis, documentation, training, and audits.
              </p>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <div className="py-12 dark:bg-gray-800 lg:py-24">
      <div className="w-full px-4 md:px-12">
        <div className="grid items-center grid-cols-3 grid-rows-1 gap-x-20">
          <div className="flex flex-col justify-center space-y-2">
            <h3 className="text-2xl font-bold tracking-tight">ISO 9001 Quality Management</h3>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              ISO 9001 is the international standard for quality management systems. It provides a framework for
              organizations to demonstrate their commitment to quality and customer satisfaction. Benefits of ISO 9001
              certification include improved operational efficiency, enhanced customer satisfaction, and access to new
              markets.
            </p>
            <Link
              className="inline-flex items-center justify-center h-8 px-4 text-xs font-medium transition-colors bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-300 dark:hover:text-gray-900 dark:focus-visible:ring-gray-300"
              rel="noopener noreferrer" target="_blank" href="https://www.iso.org/standard/62085.html">
              Learn More
            </Link>
          </div>
          <div className="flex flex-col justify-center space-y-2">
            <h3 className="text-2xl font-bold tracking-tight">ISO 14001 Environmental Management</h3>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              ISO 14001 is the international standard for environmental management systems. It helps organizations
              identify, manage, monitor, and control their environmental issues in a holistic manner. Benefits of ISO
              14001 certification include reduced environmental impact, cost savings, and improved brand reputation.
            </p>
            <Link
              className="inline-flex items-center justify-center h-8 px-4 text-xs font-medium transition-colors bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-300 dark:hover:text-gray-900 dark:focus-visible:ring-gray-300"
              rel="noopener noreferrer" target="_blank" href="https://www.iso.org/standard/60857.html">
              Learn More
            </Link>
          </div>
          <div className="flex flex-col justify-center space-y-2">
            <h3 className="text-2xl font-bold tracking-tight">IATF 16949 Automotive Quality Management</h3>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              IATF 16949 is a technical specification for automotive sector quality management systems. It aligns with ISO 9001 
              and is designed to be used in conjunction with it. Achieving IATF 16949 certification demonstrates a commitment to
               quality and continuous improvement in the automotive industry.
            </p>
            <Link
              className="inline-flex items-center justify-center h-8 px-4 text-xs font-medium transition-colors bg-white border border-gray-200 rounded-md shadow-sm hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-300 dark:hover:text-gray-900 dark:focus-visible:ring-gray-300"
              rel="noopener noreferrer" target="_blank" href="https://www.aiag.org/quality/iatf-16949-2016">
              Learn More
            </Link>
          </div>
        </div>
      </div>
    </div>
    
    <div className="py-12 lg:py-24">
      <div className="grid items-center gap-4 px-4 md:px-12">
        <div className="space-y-2 text-center lg:text-left">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Ready to get started?</h2>
          <p
            className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Contact us to learn more about our ISO certification consulting services.
          </p>
        </div>
        <div className="flex flex-col gap-2 min-[400px]:flex-row">
          <Link
            className="inline-flex items-center justify-center h-10 px-8 text-sm font-medium transition-colors bg-gray-900 rounded-md shadow text-gray-50 hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="/contact">
            Contact
          </Link>
        </div>
      </div>
    </div>
    <div className="py-12 dark:bg-gray-800 lg:py-24">
      <div className="container px-4 md:px-12">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The ISO Certification Process</h2>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our team of experienced consultants will guide you through the process, ensuring that your organization
              meets the requirements of the ISO standards. We offer a range of services to help you achieve
              certification, including gap analysis, documentation, training, and audits.
            </p>
          </div>
          <ul className="grid gap-4 py-4 list-disc md:gap-6 md:py-6">
            <li>
              <h3 className="text-xl font-bold tracking-tight">Gap Analysis and Readiness Assessment</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our consultants will conduct a thorough assessment of your organization’s current processes and
                practices to identify any gaps that need to be addressed to meet the requirements of the ISO
                standards.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Documentation and Process Improvement</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Once the gaps have been identified, our team will work with you to develop and implement the necessary
                documentation and process improvements to ensure compliance with the ISO standards.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Training and Employee Engagement</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We believe that achieving ISO certification is not just about meeting the requirements of the
                standards, but also about creating a culture of quality and continuous improvement within your
                organization. That’s why we offer training and support to help your employees understand the ISO
                standards and their role in the certification process.
              </p>
            </li>
            <li>
              <h3 className="text-xl font-bold tracking-tight">Internal Audits and Compliance Checks</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our team will conduct internal audits and compliance checks to ensure that your organization is
                meeting the requirements of the ISO standards. We will identify any areas of non-compliance and work
                with you to address them before the external certification audit.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
    {/* <div className="py-12 lg:py-24">
      <div className="container px-4 md:px-12">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px] lg:gap-12">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Clients Are Saying</h2>
            <p
              className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Don’t just take our word for it. Here are some testimonials from our clients who have successfully
              achieved ISO certification with our help.
            </p>
          </div>
          <div className="grid gap-4 md:gap-6">
            <div className="space-y-2">
              <h3 className="text-xl font-bold tracking-tight">Improved Operational Efficiency</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                “Working with the team at Acme Consulting was a game-changer for our organization. Their expertise and
                guidance helped us achieve ISO 9001 certification, and we’ve seen significant improvements in our
                operational efficiency and customer satisfaction as a result.”
              </p>
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">- John Smith, CEO, Smith & Co.</p>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold tracking-tight">Commitment to Quality</h3>
              <p
                className="text-gray-500 md:text-base/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                “The team at Acme Consulting helped us achieve ISO 14001 certification, and we couldn’t be happier
                with the results. The process was smooth and efficient, and it has helped us demonstrate our
                commitment to environmental sustainability to our customers and stakeholders.”
              </p>
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">
                - Sarah Johnson, Head of Sustainability, GreenTech Ltd.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div> */}
  </>);
}
